socialuni:
  provider:
    qq:
      qq-mp-id: "1109985787"
      qq-mp-secret: "9nybzpBQDkDgEW0Z"
      qq-merchant-id: ""
      qq-merchant-key: ""
    wx:
      wx-app-id: "wx682b729afd398217"
      wx-mp-id: "wx0bf5fe9ceeab514c"
      wx-mp-secret: "888e23c5d82cb185c433c541c43a6cea"
      wx-merchant-id: ""
      wx-merchant-key: ""
  cloud:
    tencent:
      cos:
        secret-id: "AKIDzJM9gxOoPlsmQo7pVw73kBLFtKWTGfuv"
        secret-key: "w0preCKDpwwnYAakfOxKWVFcnlV6UeYE"
        region: "ap-beijing"
        bucket-name: "devcdxapp-1257733245"
      sms:
        app-id: 1400346447
        app-key: "f00e0cab3f16d5bd30dbf7097c3d0d51"
        sms-sign: "清池交友"
        template-id: 570636
  map:
    ali:
      secret-key: "a64bc4ccb330776939d57e229ca1e63b"
server:
  port: 8097
  ssl:
    # 证书名称
    key-store: localpc.qingchiapp.com.jks
    #密钥库密码
    key-store-password: 3bu32z78qm02
    key-store-type: JKS
spring:
  datasource:
    url: jdbc:mysql://bj-cynosdbmysql-grp-8819v0ae.sql.tencentcdb.com:25014/social_demo?characterEncoding=utf-8&useSSL=false
    username: social_demo996
    password: social_demo996
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      read-only: false
      #等待连接池分配连接的最大时长（毫秒）
      connection-timeout: 600000
      #一个连接idle状态的最大时长（毫秒），超时则被释放
      idle-timeout: 600000
      #一个连接的生命时长（毫秒），超时而且没被使用则被释放
      max-lifetime: 1800000
      login-timeout: 600
      #连接池中允许的最大连接数。缺省值：10；推荐的公式：((CPU内核数量 * 2) + 硬盘数量)
      maximum-pool-size: 200
      minimum-idle: 10